// <auto-generated />
using System;
using Basestation_Software.Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basestation_Software.Api.Migrations
{
    [DbContext(typeof(REDDatabase))]
    partial class REDDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Basestation_Software.Models.Arm.ArmPresetEntity", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JointData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ArmPresets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Basestation_Software.Models.Arm.ControlPreset", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("gamepadBinds")
                        .HasColumnType("TEXT");

                    b.Property<string>("jointInversions")
                        .HasColumnType("TEXT");

                    b.Property<string>("jointSpeeds")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ControlPresets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Default",
                            gamepadBinds = "[0,1,2,3,4,5]",
                            jointInversions = "[false,false,false,false,false,false]",
                            jointSpeeds = "[0.12,1,1,1,5,5,5,0.05]"
                        });
                });

            modelBuilder.Entity("Basestation_Software.Models.Config.ConfigEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Data = "{\"Name\":\"Default\",\"Dark\":true,\"Links\":{},\"Components\":[],\"Columns\":60,\"Rows\":60,\"Width\":100,\"Height\":100}"
                        });
                });

            modelBuilder.Entity("Basestation_Software.Models.Geospatial.GPSWaypoint", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SearchRadius")
                        .HasColumnType("REAL");

                    b.Property<int?>("TagID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WaypointColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Waypoints");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Altitude = 1280.0,
                            Latitude = 38.405878999999999,
                            Longitude = -110.792207,
                            Name = "MDRS",
                            SearchRadius = 5.0,
                            Timestamp = new DateTime(2025, 4, 27, 21, 43, 36, 523, DateTimeKind.Local).AddTicks(5772),
                            Type = 0,
                            WaypointColor = -16744448
                        },
                        new
                        {
                            ID = 2,
                            Altitude = 315.0,
                            Latitude = 37.951763999999997,
                            Longitude = -91.778441000000001,
                            Name = "SDELC",
                            SearchRadius = 5.0,
                            Timestamp = new DateTime(2025, 4, 27, 21, 43, 36, 523, DateTimeKind.Local).AddTicks(5932),
                            Type = 0,
                            WaypointColor = -65536
                        });
                });

            modelBuilder.Entity("Basestation_Software.Models.Geospatial.MapTile", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<int?>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MapTiles");
                });
#pragma warning restore 612, 618
        }
    }
}
